### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 201811510210hjx** [ShubingOuyangcug/GCSANet#3]
from .baseline import *
ModuleNotFoundError: No module named 'models.baseline'

您好，我是初学者。这个报错可以怎么解决呢？

**Comment by ShubingOuyangcug** [comment]
可以考虑把这行代码在model模块注释掉，应该是不影响程序的，如果有影响在沟通

发件人：HanJiaxin ***@***.***>
发送日期：2023-02-27 10:36:24
收件人：ShubingOuyangcug/GCSANet ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[ShubingOuyangcug/GCSANet] 报错 (Issue #3)

from .baseline import *
 ModuleNotFoundError: No module named 'models.baseline'
您好，我是初学者。这个报错可以怎么解决呢？

**Comment by 201811510210hjx** [comment]
您好，可以帮忙看一下这个报错吗？一直过不去这里，真是麻烦您了。

============================================================================
Traceback (most recent call last):
  File "/home/testuser/hjx/GCSANet-main/train.py", line 260, in <module>
    main()
  File "/home/testuser/hjx/GCSANet-main/train.py", line 45, in main
    mkdir_p(args.checkpoint)
  File "/home/testuser/hjx/GCSANet-main/utils/misc.py", line 59, in mkdir_p
    os.makedirs(path)
  File "/home/Anaconda3/envs/wzh/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/Anaconda3/envs/wzh/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/Anaconda3/envs/wzh/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 4 more times]
  File "/home/Anaconda3/envs/wzh/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/run/media/cug'
